# **LAB 01-Feed Forward & Back-Propagation Learning Algorithm**

### **20th January 2025**
# **REDDIPALLI SAI CHARISH**
# **CS22B1095**


---



---



---







#**QUESTION-1**
Implement the Perceptron algorithm from scratch in Python.
*   Initialize the weights with [0 0 0] and a learning rate of 0.0001.
*   For each iteration, calculate the output of the Perceptron for each input in the training set.
*  Use MSE to computer the error for all samples
* Update the weights using the gradient descent procedure.
*   Repeat the above steps until the Perceptron converges or a maximum number of iterations is reached.
* Test the trained Perceptron on a separate test set, explain how you came up with the test set.
* Use the step function as an  activation function in the output layer
Use the IRIS Dataset for the above, considering all four features: sepal length, sepal width, petal length, and petal width, but only two classes -  Setosa, and Versicolor.  Drop the feature vectors of the other class.


In [1]:
#importing necessary libraries
import numpy as np
import pandas as pd

## **Perceptron**

In [2]:
#defining single layer perceptronm as Class
class Perceptron:
  def __init__(self,lr=0.0001, epochs=100):
    self.lr = lr
    self.epochs = epochs
    self.acv_func = self.step_func
    self.w = None

  def step_func(self, x):
    return np.where(x >= 0, 1, 0)

  def fit(self,X,y):
    X=np.insert(X,0,1,axis=1)
    n_samples,n_features = X.shape
    self.w = np.zeros(n_features)

    while self.epochs > 0:
      flag = 0
      for i,x_i in enumerate(X):
        dot_output = np.dot(x_i,self.w)
        y_pred = self.acv_func(dot_output)
        if y_pred != y[i]:
          self.w += self.lr * (y[i] - y_pred) * x_i
          flag = 1
      if flag == 0:
        break
      self.epochs -= 1

  def predict(self,X):
    X=np.insert(X,0,1,axis=1)
    return self.acv_func(np.dot(X,self.w))


In [3]:
#managing the dataset
iris_df = pd.read_csv("iris.csv").drop("Id", axis=1)
iris_df = iris_df[iris_df['Species'].isin(['Iris-setosa', 'Iris-versicolor'])]
print(f"Count: {len(iris_df)}")
iris_df

Count: 100


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
0             5.1           3.5            1.4           0.2      Iris-setosa
1             4.9           3.0            1.4           0.2      Iris-setosa
2             4.7           3.2            1.3           0.2      Iris-setosa
3             4.6           3.1            1.5           0.2      Iris-setosa
4             5.0           3.6            1.4           0.2      Iris-setosa
..            ...           ...            ...           ...              ...
95            5.7           3.0            4.2           1.2  Iris-versicolor
96            5.7           2.9            4.2           1.3  Iris-versicolor
97            6.2           2.9            4.3           1.3  Iris-versicolor
98            5.1           2.5            3.0           1.1  Iris-versicolor
99            5.7           2.8            4.1           1.3  Iris-versicolor

[100 rows x 5 columns]

In [4]:
#giving setos as 0 and versicolor as 1
X = iris_df.drop("Species", axis=1).values
y = iris_df['Species'].map({'Iris-setosa': 0, 'Iris-versicolor': 1}).values

In [5]:
#test train split
def train_test_split(X, y, test_size=0.9):
    n_classes = len(np.unique(y))
    X_train, X_test, y_train, y_test = [], [], [], []
    for i in range(n_classes):
        X_class = X[y == i]
        y_class = y[y == i]
        n_samples = len(X_class)
        n_train = int(n_samples * (1 - test_size))
        X_train.extend(X_class[:n_train])
        X_test.extend(X_class[n_train:])
        y_train.extend(y_class[:n_train])
        y_test.extend(y_class[n_train:])
    return np.array(X_train), np.array(X_test), np.array(y_train), np.array(y_test)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print("Test dataset for each class:")
print(f"{np.asarray(np.unique(y_test, return_counts=True)).T}")



Test dataset for each class:
[[ 0 10]
 [ 1 10]]


In [6]:
#Calling the perceptron
perceptron=Perceptron(lr=0.0001,epochs=100)
perceptron.fit(X_train,y_train)

In [7]:
#Prediciting the values with accuracy
y_pred=perceptron.predict(X_test)
result=pd.DataFrame({'Actual':y_test,'Predicted':y_pred})
result


Actual  Predicted
0        0          0
1        0          0
2        0          0
3        0          0
4        0          0
5        0          0
6        0          0
7        0          0
8        0          0
9        0          0
10       1          1
11       1          1
12       1          1
13       1          1
14       1          1
15       1          1
16       1          1
17       1          1
18       1          1
19       1          1

In [8]:
accuracy=np.mean(y_pred==y_test)*100
accuracy

100.0

# **QUESTION 2**
Implement the feedforward and backpropagation learning algorithm for multiple perceptrons in Python for the question provided in the attached image.



*   Initialize the weights and biases randomly.

*  Implement the forward pass.

*   Compute the loss between the predicted output and the actual output using an appropriate loss function.
*  Compute the loss between the predicted output and the actual output using an appropriate loss function.


*   Update the weights and biases.


*   Iterate over multiple times (epochs), performing forward propagation, loss calculation, backpropagation, and parameter updates in each iteration till convergence.



In [9]:
# np.set_printoptions(suppress=True, precision=4)

##Initialize the weights and biases randomly.

In [10]:

w_0 = np.array([[0.5, 1.5, 0.8], [0.8, 0.2, -1.6]])
w_1 = np.array([[0.9, -1.7, 1.6], [1.2, 2.1, -0.2]])

##feature vectors

In [11]:
X1 = np.array([1.0, 0.7, 1.2])
X2 = np.array([1.0, 0.0, 0.0])
t = np.array([1.0, 0.0])

##sigmoid function

In [12]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [13]:
def sigmoid_output(y: np.array):
    return np.array([1 if i > 0.5 else 0 for i in y])

##Implement the forward pass.

In [14]:
def feed_forward(feature_vector, weight_vector):
    return sigmoid(np.dot(weight_vector, feature_vector))

## Back Propogation

In [15]:
def back_propagation(W, X, delta_vector, lr):
    n, m = W.shape
    for j in range(n):
        for i in range(m):
            W[j, i] = W[j, i] - lr * delta_vector[j] * X[i]
    return W

In [16]:
def delta_hidden_layer(next_delta_vector, W, output_vector):
    n, m = W.shape
    delta_vector = np.zeros(m - 1)

    for i in range(m - 1):
        for j in range(n):
            delta_vector[j] += next_delta_vector[i] * W[i , j + 1]

    delta_vector = output_vector * (1 - output_vector) * delta_vector
    return delta_vector

##Multi Layer Perceptron

In [17]:
def mlp(X1, X2, w_0, w_1, t, lr=0.001, epochs=1000):
    for epoch in range(epochs):
        print(f"Epoch {epoch + 1}")
        o1 = feed_forward(X1, w_0)
        X2[1], X2[2] = o1[0], o1[1]
        o2 = feed_forward(X2, w_1)
        output = sigmoid_output(o2)
        mse = np.mean((t - o2) ** 2)
        print(f"Mean Squared Error after epoch {epoch + 1}: {mse:.4f}")

        # print(f"Output after epoch {epoch + 1}: {o2}")
        print(f"Output after epoch {epoch + 1}: {output}")

        # if np.array_equal(o2, t):
        if np.array_equal(output, t):
            print(f"Converged after {epoch + 1} epochs")
            break
        else:
            delta_2_vector = (o2 - t) * o2 * (1 - o2)
            print(f"Delta 2: {delta_2_vector}")
            w_1 = back_propagation(w_1, X2, delta_2_vector, lr)
            print("O1 : ", o1)
            delta_1_vector = delta_hidden_layer(delta_2_vector, w_1, o1)
            print(f"Delta 1: {delta_1_vector}")
            w_0 = back_propagation(w_0, X1, delta_1_vector, lr)

        print(f"Updated weights after epoch {epoch + 1}:")
        print(f"w_0: {w_0}")
        print(f"w_1: {w_1}\n")
    else:
        print("Did not converge after max epochs")

    return w_0, w_1


In [18]:
w_0, w_1 = mlp(X1, X2, w_0, w_1, t, 0.5, 1000)
print("")
print("")

print("Final weight vector:")
print("w_0:", w_0)
print("w_1:", w_1)

Epoch 1
Mean Squared Error after epoch 1: 0.6134
Output after epoch 1: [0 1]
Delta 2: [-0.13773709  0.03989946]
O1 :  [0.92483989 0.27289178]
Delta 1: [ 0.02143951 -0.0458682 ]
Updated weights after epoch 1:
w_0: [[ 0.48928025  1.49249617  0.7871363 ]
 [ 0.8229341   0.21605387 -1.57247908]]
w_1: [[ 0.96886855 -1.63630762  1.61879366]
 [ 1.18005027  2.08154969 -0.20544412]]

Epoch 2
Mean Squared Error after epoch 2: 0.5903
Output after epoch 2: [0 1]
Delta 2: [-0.12962753  0.04151728]
O1 :  [0.92262728 0.28642658]
Delta 1: [ 0.02070085 -0.0451741 ]
Updated weights after epoch 2:
w_0: [[ 0.47892982  1.48525087  0.77471578]
 [ 0.84552115  0.2318648  -1.54537462]]
w_1: [[ 1.03368231 -1.57650867  1.63735805]
 [ 1.15929163  2.0623972  -0.21138994]]

Epoch 3
Mean Squared Error after epoch 3: 0.5694
Output after epoch 3: [1 1]
Delta 2: [-0.1202092   0.04325064]
O1 :  [0.92043444 0.30014173]
Delta 1: [ 0.01986128 -0.04377949]
Updated weights after epoch 3:
w_0: [[ 0.46899918  1.47829943  0.7627